/*
 * This file is generated by jOOQ.
 */
package com.example.demo.dao.jooq.tables.records;


import com.example.demo.dao.jooq.tables.JobHistory;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobHistoryRecord extends TableRecordImpl<JobHistoryRecord> implements Record5<UInteger, LocalDate, LocalDate, String, UInteger> {

    private static final long serialVersionUID = -1931161355;

    /**
     * Setter for <code>hr.job_history.employee_id</code>.
     */
    public void setEmployeeId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>hr.job_history.employee_id</code>.
     */
    public UInteger getEmployeeId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>hr.job_history.start_date</code>.
     */
    public void setStartDate(LocalDate value) {
        set(1, value);
    }

    /**
     * Getter for <code>hr.job_history.start_date</code>.
     */
    public LocalDate getStartDate() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>hr.job_history.end_date</code>.
     */
    public void setEndDate(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>hr.job_history.end_date</code>.
     */
    public LocalDate getEndDate() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>hr.job_history.job_id</code>.
     */
    public void setJobId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>hr.job_history.job_id</code>.
     */
    public String getJobId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>hr.job_history.department_id</code>.
     */
    public void setDepartmentId(UInteger value) {
        set(4, value);
    }

    /**
     * Getter for <code>hr.job_history.department_id</code>.
     */
    public UInteger getDepartmentId() {
        return (UInteger) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<UInteger, LocalDate, LocalDate, String, UInteger> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<UInteger, LocalDate, LocalDate, String, UInteger> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<UInteger> field1() {
        return JobHistory.JOB_HISTORY.EMPLOYEE_ID;
    }

    @Override
    public Field<LocalDate> field2() {
        return JobHistory.JOB_HISTORY.START_DATE;
    }

    @Override
    public Field<LocalDate> field3() {
        return JobHistory.JOB_HISTORY.END_DATE;
    }

    @Override
    public Field<String> field4() {
        return JobHistory.JOB_HISTORY.JOB_ID;
    }

    @Override
    public Field<UInteger> field5() {
        return JobHistory.JOB_HISTORY.DEPARTMENT_ID;
    }

    @Override
    public UInteger component1() {
        return getEmployeeId();
    }

    @Override
    public LocalDate component2() {
        return getStartDate();
    }

    @Override
    public LocalDate component3() {
        return getEndDate();
    }

    @Override
    public String component4() {
        return getJobId();
    }

    @Override
    public UInteger component5() {
        return getDepartmentId();
    }

    @Override
    public UInteger value1() {
        return getEmployeeId();
    }

    @Override
    public LocalDate value2() {
        return getStartDate();
    }

    @Override
    public LocalDate value3() {
        return getEndDate();
    }

    @Override
    public String value4() {
        return getJobId();
    }

    @Override
    public UInteger value5() {
        return getDepartmentId();
    }

    @Override
    public JobHistoryRecord value1(UInteger value) {
        setEmployeeId(value);
        return this;
    }

    @Override
    public JobHistoryRecord value2(LocalDate value) {
        setStartDate(value);
        return this;
    }

    @Override
    public JobHistoryRecord value3(LocalDate value) {
        setEndDate(value);
        return this;
    }

    @Override
    public JobHistoryRecord value4(String value) {
        setJobId(value);
        return this;
    }

    @Override
    public JobHistoryRecord value5(UInteger value) {
        setDepartmentId(value);
        return this;
    }

    @Override
    public JobHistoryRecord values(UInteger value1, LocalDate value2, LocalDate value3, String value4, UInteger value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JobHistoryRecord
     */
    public JobHistoryRecord() {
        super(JobHistory.JOB_HISTORY);
    }

    /**
     * Create a detached, initialised JobHistoryRecord
     */
    public JobHistoryRecord(UInteger employeeId, LocalDate startDate, LocalDate endDate, String jobId, UInteger departmentId) {
        super(JobHistory.JOB_HISTORY);

        set(0, employeeId);
        set(1, startDate);
        set(2, endDate);
        set(3, jobId);
        set(4, departmentId);
    }
}
