/*
 * This file is generated by jOOQ.
 */
package com.example.demo.dao.jooq.tables.records;


import com.example.demo.dao.jooq.tables.Locations;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LocationsRecord extends UpdatableRecordImpl<LocationsRecord> implements Record6<UInteger, String, String, String, String, String> {

    private static final long serialVersionUID = 1656402787;

    /**
     * Setter for <code>hr.locations.location_id</code>.
     */
    public void setLocationId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>hr.locations.location_id</code>.
     */
    public UInteger getLocationId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>hr.locations.street_address</code>.
     */
    public void setStreetAddress(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>hr.locations.street_address</code>.
     */
    public String getStreetAddress() {
        return (String) get(1);
    }

    /**
     * Setter for <code>hr.locations.postal_code</code>.
     */
    public void setPostalCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>hr.locations.postal_code</code>.
     */
    public String getPostalCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>hr.locations.city</code>.
     */
    public void setCity(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>hr.locations.city</code>.
     */
    public String getCity() {
        return (String) get(3);
    }

    /**
     * Setter for <code>hr.locations.state_province</code>.
     */
    public void setStateProvince(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>hr.locations.state_province</code>.
     */
    public String getStateProvince() {
        return (String) get(4);
    }

    /**
     * Setter for <code>hr.locations.country_id</code>.
     */
    public void setCountryId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>hr.locations.country_id</code>.
     */
    public String getCountryId() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<UInteger, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UInteger, String, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UInteger> field1() {
        return Locations.LOCATIONS.LOCATION_ID;
    }

    @Override
    public Field<String> field2() {
        return Locations.LOCATIONS.STREET_ADDRESS;
    }

    @Override
    public Field<String> field3() {
        return Locations.LOCATIONS.POSTAL_CODE;
    }

    @Override
    public Field<String> field4() {
        return Locations.LOCATIONS.CITY;
    }

    @Override
    public Field<String> field5() {
        return Locations.LOCATIONS.STATE_PROVINCE;
    }

    @Override
    public Field<String> field6() {
        return Locations.LOCATIONS.COUNTRY_ID;
    }

    @Override
    public UInteger component1() {
        return getLocationId();
    }

    @Override
    public String component2() {
        return getStreetAddress();
    }

    @Override
    public String component3() {
        return getPostalCode();
    }

    @Override
    public String component4() {
        return getCity();
    }

    @Override
    public String component5() {
        return getStateProvince();
    }

    @Override
    public String component6() {
        return getCountryId();
    }

    @Override
    public UInteger value1() {
        return getLocationId();
    }

    @Override
    public String value2() {
        return getStreetAddress();
    }

    @Override
    public String value3() {
        return getPostalCode();
    }

    @Override
    public String value4() {
        return getCity();
    }

    @Override
    public String value5() {
        return getStateProvince();
    }

    @Override
    public String value6() {
        return getCountryId();
    }

    @Override
    public LocationsRecord value1(UInteger value) {
        setLocationId(value);
        return this;
    }

    @Override
    public LocationsRecord value2(String value) {
        setStreetAddress(value);
        return this;
    }

    @Override
    public LocationsRecord value3(String value) {
        setPostalCode(value);
        return this;
    }

    @Override
    public LocationsRecord value4(String value) {
        setCity(value);
        return this;
    }

    @Override
    public LocationsRecord value5(String value) {
        setStateProvince(value);
        return this;
    }

    @Override
    public LocationsRecord value6(String value) {
        setCountryId(value);
        return this;
    }

    @Override
    public LocationsRecord values(UInteger value1, String value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LocationsRecord
     */
    public LocationsRecord() {
        super(Locations.LOCATIONS);
    }

    /**
     * Create a detached, initialised LocationsRecord
     */
    public LocationsRecord(UInteger locationId, String streetAddress, String postalCode, String city, String stateProvince, String countryId) {
        super(Locations.LOCATIONS);

        set(0, locationId);
        set(1, streetAddress);
        set(2, postalCode);
        set(3, city);
        set(4, stateProvince);
        set(5, countryId);
    }
}
