/*
 * This file is generated by jOOQ.
 */
package com.example.demo.dao.jooq;


import com.example.demo.dao.jooq.tables.*;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Hr extends SchemaImpl {

    private static final long serialVersionUID = 561868044;

    /**
     * The reference instance of <code>hr</code>
     */
    public static final Hr HR = new Hr();

    /**
     * The table <code>hr.countries</code>.
     */
    public final Countries COUNTRIES = Countries.COUNTRIES;

    /**
     * The table <code>hr.departments</code>.
     */
    public final Departments DEPARTMENTS = Departments.DEPARTMENTS;

    /**
     * The table <code>hr.employees</code>.
     */
    public final Employees EMPLOYEES = Employees.EMPLOYEES;

    /**
     * The table <code>hr.job_history</code>.
     */
    public final JobHistory JOB_HISTORY = JobHistory.JOB_HISTORY;

    /**
     * The table <code>hr.jobs</code>.
     */
    public final Jobs JOBS = Jobs.JOBS;

    /**
     * The table <code>hr.locations</code>.
     */
    public final Locations LOCATIONS = Locations.LOCATIONS;

    /**
     * The table <code>hr.regions</code>.
     */
    public final Regions REGIONS = Regions.REGIONS;

    /**
     * No further instances allowed
     */
    private Hr() {
        super("hr", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Countries.COUNTRIES,
            Departments.DEPARTMENTS,
            Employees.EMPLOYEES,
            JobHistory.JOB_HISTORY,
            Jobs.JOBS,
            Locations.LOCATIONS,
            Regions.REGIONS);
    }
}
