/*
 * This file is generated by jOOQ.
 */
package com.example.demo.dao.jooq;


import com.example.demo.dao.jooq.tables.Countries;
import com.example.demo.dao.jooq.tables.Departments;
import com.example.demo.dao.jooq.tables.Employees;
import com.example.demo.dao.jooq.tables.JobHistory;
import com.example.demo.dao.jooq.tables.Locations;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>hr</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index COUNTRIES_REGION_ID = Indexes0.COUNTRIES_REGION_ID;
    public static final Index DEPARTMENTS_LOCATION_ID = Indexes0.DEPARTMENTS_LOCATION_ID;
    public static final Index EMPLOYEES_DEPARTMENT_ID = Indexes0.EMPLOYEES_DEPARTMENT_ID;
    public static final Index EMPLOYEES_JOB_ID = Indexes0.EMPLOYEES_JOB_ID;
    public static final Index JOB_HISTORY_DEPARTMENT_ID = Indexes0.JOB_HISTORY_DEPARTMENT_ID;
    public static final Index JOB_HISTORY_JOB_ID = Indexes0.JOB_HISTORY_JOB_ID;
    public static final Index LOCATIONS_COUNTRY_ID = Indexes0.LOCATIONS_COUNTRY_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index COUNTRIES_REGION_ID = Internal.createIndex("region_id", Countries.COUNTRIES, new OrderField[] { Countries.COUNTRIES.REGION_ID }, false);
        public static Index DEPARTMENTS_LOCATION_ID = Internal.createIndex("location_id", Departments.DEPARTMENTS, new OrderField[] { Departments.DEPARTMENTS.LOCATION_ID }, false);
        public static Index EMPLOYEES_DEPARTMENT_ID = Internal.createIndex("department_id", Employees.EMPLOYEES, new OrderField[] { Employees.EMPLOYEES.DEPARTMENT_ID }, false);
        public static Index EMPLOYEES_JOB_ID = Internal.createIndex("job_id", Employees.EMPLOYEES, new OrderField[] { Employees.EMPLOYEES.JOB_ID }, false);
        public static Index JOB_HISTORY_DEPARTMENT_ID = Internal.createIndex("department_id", JobHistory.JOB_HISTORY, new OrderField[] { JobHistory.JOB_HISTORY.DEPARTMENT_ID }, false);
        public static Index JOB_HISTORY_JOB_ID = Internal.createIndex("job_id", JobHistory.JOB_HISTORY, new OrderField[] { JobHistory.JOB_HISTORY.JOB_ID }, false);
        public static Index LOCATIONS_COUNTRY_ID = Internal.createIndex("country_id", Locations.LOCATIONS, new OrderField[] { Locations.LOCATIONS.COUNTRY_ID }, false);
    }
}
