/*
 * This file is generated by jOOQ.
 */
package com.example.demo.dao.jooq;


import com.example.demo.dao.jooq.tables.Countries;
import com.example.demo.dao.jooq.tables.Departments;
import com.example.demo.dao.jooq.tables.Employees;
import com.example.demo.dao.jooq.tables.JobHistory;
import com.example.demo.dao.jooq.tables.Jobs;
import com.example.demo.dao.jooq.tables.Locations;
import com.example.demo.dao.jooq.tables.Regions;


/**
 * Convenience access to all tables in hr
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>hr.countries</code>.
     */
    public static final Countries COUNTRIES = Countries.COUNTRIES;

    /**
     * The table <code>hr.departments</code>.
     */
    public static final Departments DEPARTMENTS = Departments.DEPARTMENTS;

    /**
     * The table <code>hr.employees</code>.
     */
    public static final Employees EMPLOYEES = Employees.EMPLOYEES;

    /**
     * The table <code>hr.job_history</code>.
     */
    public static final JobHistory JOB_HISTORY = JobHistory.JOB_HISTORY;

    /**
     * The table <code>hr.jobs</code>.
     */
    public static final Jobs JOBS = Jobs.JOBS;

    /**
     * The table <code>hr.locations</code>.
     */
    public static final Locations LOCATIONS = Locations.LOCATIONS;

    /**
     * The table <code>hr.regions</code>.
     */
    public static final Regions REGIONS = Regions.REGIONS;
}
